### ISSUE TITLE
Event shown as location restricted 

### ISSUE THREAD

**Issue by camillestmartin** [iBurnApp/iBurn-iOS#119]
Hey there!! I know this is a total shot in the dark but you will help a lot of women seeking information about squirting!! Lol. I am camped with a large Esplanade camp, we are a kinky circus camp. There was an error in the location of one our bigger events. The event is called SquirtWorks - the organizers put on the similar squirting workshop at Love Burn and it was a wildly popular event! We were really hoping to get the word out.

 For some reason the location says "Brulee Bacon Brunch" (which is one of our events) instead of our location which is Brulee. On the app it says Location Restricted. Not sure why it listed that way on Playa Events or why it pulled that way onto the app. Is there any way to fix this??? OR my roommate is with us he is a software developer he could help fix it too. Anyways, I know everyone is busy getting ready and leaving for the Burn but just thought I'd try!!!!! 

https://playaevents.burningman.org/2022/playa_event/40783/

**Comment by chrisballinger** [comment]
Unfortunately playa locations are restricted until gates open due to restrictions imposed by the Burning Man organization. Check back while on playa 8+ days from now!

**Comment by camillestmartin** [comment]
Hi there, yes but the location/camp is wrong. Should be listed under
Brulee!!!!

**Comment by camillestmartin** [comment]
For some reason it didn't pull into all our other events at camp. The other
events say hosted by Brulee.

**Comment by chrisballinger** [comment]
Ah that's likely an issue with how it was submitted to PlayaEvents. Whoever submitted that event should try to edit it here: https://playaevents.burningman.org

If it still is messed up on the PlayaEvents website, then you might want to try contacting someone from the Burning Man tech team: https://playaevents.burningman.org/help/

Unfortunately it's likely too late for any updates to be reflected in the app this year - sorry!

**Comment by camillestmartin** [comment]
No worries, thanks for the update!
