### ISSUE TITLE
Incorrect time slots for events

### ISSUE THREAD

**Issue by Ecosensualsapothecary** [iBurnApp/iBurn-iOS#120]
Hello, 

i am unsure if this is a bug in the app, but there are several incorrect times for events. 

For Afterglow Lounge & Spa, here is what it should be altered to:
-opening tea ritual Monday 8/29 from 2:30pm-4pm
-ecosexuality workshop Tuesday 8/30 from 7-8pm
-wildcrafted intuitive magick workshop Wednesday 8/31 from 8-9pm
-closing tea ritual Saturday 9/3 from 11am-12am

**Comment by chrisballinger** [comment]
Please submit your changes to PlayaEvents directly: https://playaevents.burningman.org/playa_event/search/2022/?q=Afterglow+Lounge+%26+Spa
