### ISSUE TITLE
All our camp events are missing

### ISSUE THREAD

**Issue by LAdrenalina** [iBurnApp/iBurn-iOS#123]
Hey Guys, thank you for this fantastic app. I went to check our camp events and sadly they’re missing :( could you please add them? Here is a link to them in the WhatWhereWhen guide - https://playaevents.burningman.org/playa_event/search/2022/?q=Tea+cat

**Comment by chrisballinger** [comment]
I see them in the iOS app. Can you make sure to update to the most recent version?

**Comment by chrisballinger** [comment]
If we make it out there this year, we'd love to stop by!

**Comment by LAdrenalina** [comment]
Chris,

Thank you for writing back! I did originally update the app and I could see our camp but not our events, but completely removing and re-installing the app did the trick.

I really hope you make it out and come visit us!!! Also, thank you so so much for making this app. It’s been so incredibly helpful on the Playa for someone like me with no sense of direction. You guys rock and your gift is greatly appreciated!!

Sincerely,
Red Panther
