### ISSUE TITLE
Plaza geocoder issue

### ISSUE THREAD

**Issue by chrisballinger** [iBurnApp/iBurn-iOS#126]
Plaza camps (9:00 & G Plaza, 6:00 & G Plaza) are appearing at the 3:00 & B Plaza

**Comment by justinormont** [comment]
This also occurs in the Android version. Hence the right repo for this issue may be one of the common iBurnApp repos (e.g. [iBurn-Data](https://github.com/iBurnApp/iBurn-Data) / [BlackRockCityPlanner](https://github.com/iBurnApp/BlackRockCityPlanner)). 

An example -- `9:00 B Plaza` is geocoded to the `3:00 B Plaza`:
![Screenshot_20220902-221225](https://user-images.githubusercontent.com/4080826/189035124-231e1389-0ba1-405c-92b7-82afeefa04f3.png)

**Comment by chrisballinger** [comment]
Thanks! Yeah this is due to the geocoder
