### ISSUE TITLE
Our events and camp are missing - Kreme Burners

### ISSUE THREAD

**Issue by sideshowbill** [iBurnApp/iBurn-iOS#127]
Our camp and events are missing from the app. Our camp is a the Kreme Burners  and the events are ”Krème Brûlée and Chill” and “Peaches N Cream”. We are listed in the official guide so not sure what happened. We would love to delight  everyone with our guest of  crème brûlée’s and peaches and cream so we would be very grateful if you could get us included into the app this year. Thank you for making this wonderful app!!! We look forward to seeing you in the dust soon! We’re located at 6&F

**Comment by chrisballinger** [comment]
Does it show up here? https://playaevents.burningman.org/

It's too late to add new events unfortunately but we'll try to stop by because you're in the neighborhood!
