### ISSUE TITLE
Current location as measure of feet from man was inaccurate 

### ISSUE THREAD

**Issue by mjerris** [iBurnApp/iBurn-iOS#138]
When looking at your current location as clock time and feet from man, the distance from man calculation was way off numbers were about 50% higher than they should be.  man to a point on trash fence should be 8175’

**Comment by chrisballinger** [comment]
Hmmm yeah you're right! I tried Point 1 - 40.782814, -119.233566 from here https://bm-innovate.s3.amazonaws.com/2023/2023%20BRC%20Measurements.pdf and it shows it as 7:12 & 13535' from the man. On the bottom of that document it says for this year the points should be 8,430' from the man
![Simulator Screenshot - iPhone 14 Pro - 2023-08-06 at 07 59 00](https://github.com/iBurnApp/iBurn-iOS/assets/518687/c7b5d465-173d-4b24-a302-3fa8e1951b35)

If you're able to help us debug, the source code for the geocoder is here: https://github.com/iBurnApp/BlackRockCityPlanner/tree/master/src/geocoder
and our layout file is here: https://github.com/iBurnApp/iBurn-Data/tree/master/data/2023/layouts

cc @davidchiles

**Comment by objectiveSee** [comment]
Do you have a script that builds those layout json files from the 2023 API?

**Comment by chrisballinger** [comment]
That layout file is actually artisanal hand crafted JSON, it is used to generate GeoJSON and also within the geocoder

**Comment by objectiveSee** [comment]
mmm love artisinal json ;) 

Thank you! Big fan of the app.

**Comment by andyland** [comment]
@chrisballinger Fix is here: https://github.com/iBurnApp/BlackRockCityPlanner/pull/5

**Comment by chrisballinger** [comment]
fixed in latest release, thank you!
