### ISSUE TITLE
Incomplete label

### ISSUE THREAD

**Issue by bjeppson** [iBurnApp/iBurn-iOS#141]
A label is incomplete. 
“Navigation Mode
Keep screen on when map is . . .”
Tapping it should give more info but nothing happens. 
![IMG_9276](https://github.com/iBurnApp/iBurn-iOS/assets/31866441/c23f3b01-66bf-4ac4-b4b4-f1b324bd8c23)

**Comment by chrisballinger** [comment]
Thanks for the report! This will be fixed in the next release, the full string is "Keep screen on when map is visible"
