### ISSUE TITLE
Days are wrong

### ISSUE THREAD

**Issue by skaag** [iBurnApp/iBurn-iOS#164]
8/27 shows as Sunday, but this year it's on a Tuesday. Please fix ❤️🔥

![image](https://github.com/user-attachments/assets/5b5304db-c87b-4ff8-83e0-46ef171844bb)

**Comment by chrisballinger** [comment]
That’s the 2023 version, the 2024 version is still in beta. Feel free to sign up here for the beta or wait for the App Store release soon: https://testflight.apple.com/join/WQTaAUGk
