### ISSUE TITLE
Please add schedule 

### ISSUE THREAD

**Issue by dvnovoselov** [iBurnApp/iBurn-iOS#174]
Hello,

I’m a builder at the Temple of Love Camp, located at 7:45 & B. We have a program scheduled and would like to have it added to the IBurn app.

Please let me know if you need any additional information from us to make this happen.

Thank you for your assistance!
![IMG_3669](https://github.com/user-attachments/assets/72e4c532-884b-4bca-bd65-3a64facfc9a5)

**Comment by chrisballinger** [comment]
unfortunately we can't add new events at this point, they must be submitted in advance to playevents by 8/9: https://playaevents.burningman.org/
