### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by chrisballinger** [iBurnApp/iBurn-iOS#38]
The googles they do nothing!

**Comment by chrisballinger** [comment]
Tried implementing with DKNightVersion but it screwed up the UI. Let's try again in 2016.

**Comment by davidchiles** [comment]
👍🏼 if vector tiles happen it should be easy to have a night mode map as well.

**Comment by chrisballinger** [comment]
Google maps just added night mode on iOS and its super nice

**Comment by deeje** [comment]
+1

**Comment by chrisballinger** [comment]
fixed
