### ISSUE TITLE
Feature Request re: Favorites ❤️  - three tabs at the top: 🕝 Events | ⛺️Camps | 🎨Art

### ISSUE THREAD

**Issue by muloka** [iBurnApp/iBurn-iOS#85]
For those of us with lots of events or camps that we've favorited, scrolling through the one list can be long.

Splitting it out into three separate spaces could be nice.

Default tab to Events

**Comment by chrisballinger** [comment]
Oh yeah that's a good idea, it definitely gets kinda clogged up. I also should have implemented a "quick scroll" bar on the right.

**Comment by chrisballinger** [comment]
Done!

**Comment by muloka** [comment]
Amazing thanks! Didn't go this year though love that this got implemented.

**Comment by chrisballinger** [comment]
@muloka next year was better anyway
