### ISSUE TITLE
Art Tour

### ISSUE THREAD

**Issue by diablodiablo** [iBurnApp/iBurn-iOS#96]
Art tour is not loading
It tries and then says nothing available 

There is a link to the SoundCloud which is great off Playa but not so much when you are actually at the art

**Comment by chrisballinger** [comment]
The offline audio tour isn't included in the App Store version, it is
coming in the next update

**Comment by diablodiablo** [comment]
Same thing this year I’m guessing? ;)

Saw that it just got posted to SoundCloud (link on the app takes you to 2018 still though)
